### PR TITLE
Feature/tsosplitting

### PR DESCRIPTION
**Pull request by rebeccahaines1**
Split TSO samplesheets and run pipeline multiple times. Use updated TSO app and duty CSV apps

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/507)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/507)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @rebeccahaines1)

___
*[`upload_and_setoff_workflows.py` line 384 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/507#-Nh2LjnwB6jLLSXogvdx:-Nh2LjnxCq2mDHUIG5BL:b58bolv) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/b5bc093e5cd853b5c22cddfb2016234f94094794/upload_and_setoff_workflows.py#L384)):*
> ```Python
>                 if TSO500_sample_list:
>                     # split TSO samplesheet  to multiple sheets with <=16 samples/sheet
>                     self.TSO500_samplesheets_list = self.split_TSO500_sampleheet()
> ```

typo (but it's consistent!)



_Suggestion:_
```Python
sampleheet
```
___
*[`upload_and_setoff_workflows.py` line 655 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/507#-Nh2LwOXDpINzoDwRG5K:-Nh2LwOXDpINzoDwRG5L:b-41cpzx) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/b5bc093e5cd853b5c22cddfb2016234f94094794/upload_and_setoff_workflows.py#L655)):*
> ```Python
> 
>         # Separate header from samples. TSO samplesheet header is the first 25 lines of the file
>         samplesheet_header = all_lines[:25]
> ```

is this a reliable way of extracting this? rather can we read until we get to the expected header (like the opposite of what is done here https://github.com/moka-guys/automate_demultiplex/blob/b5bc093e5cd853b5c22cddfb2016234f94094794/upload_and_setoff_workflows.py#L625)
___
*[`upload_and_setoff_workflows.py` line 660 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/507#-Nh2NXXP7Y4wdnPum5FX:-Nh2NXXP7Y4wdnPum5FY:b-7m9pri) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/b5bc093e5cd853b5c22cddfb2016234f94094794/upload_and_setoff_workflows.py#L660)):*
> ```Python
> 
>         # Split samples into batches (size specified in config)
>         batches = [samples[i:i + config.batch_size] for i in range(0, len(samples), config.batch_size)]
> ```

neat!
___
*[`upload_and_setoff_workflows.py` line 660 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/507#-Nh2Nr8sDCY0Hje0f0fz:-Nh2Nr8sDCY0Hje0f0g-:b-2uyttm) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/b5bc093e5cd853b5c22cddfb2016234f94094794/upload_and_setoff_workflows.py#L660)):*
> ```Python
> 
>         # Split samples into batches (size specified in config)
>         batches = [samples[i:i + config.batch_size] for i in range(0, len(samples), config.batch_size)]
> ```

can we add a comment just saying batches is a list of lists, where each list is a list of lines from the sampelsheet (I think it is anyway!)
___
*[`upload_and_setoff_workflows.py` line 1705 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/507#-Nh2QABz3oZ-xed0snoa:-Nh2QABz3oZ-xed0snob:bjb7zw1) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/b5bc093e5cd853b5c22cddfb2016234f94094794/upload_and_setoff_workflows.py#L1705)):*
> ```Python
>             # remove any None values from the command_list
>             TSO500_commands.writelines(
>                 [line + "\n" for line in filter(None, TSOcommands_list)]
> ```

why would there be any Nones?
___
*[`upload_and_setoff_workflows.py` line 1923 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/507#-Nh2PE3x5QuP_JvgVows:-Nh2PE3x5QuP_JvgVowt:b-wa7hzl) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/b5bc093e5cd853b5c22cddfb2016234f94094794/upload_and_setoff_workflows.py#L1923)):*
> ```Python
>         )
>         # capture any pan numbers that are a highthroughput assay
>         high_throughput_list = [
> ```

should we review the instance type used? eg go to a smaller/middle instance type in all cases?
___
*[`upload_and_setoff_workflows.py` line 1958 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/507#-Nh2Ow5199DeW7Ws79bx:-Nh2Ow5199DeW7Ws79by:b-mgydsb) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/b5bc093e5cd853b5c22cddfb2016234f94094794/upload_and_setoff_workflows.py#L1958)):*
> ```Python
>             config.TSO500_project_name_stage,
>             self.runfolder_obj.nexus_project_name,
>             config.TSO500_runfolder_name_stage, 
> ```

I guess this is a new input to app?

**Review by rebeccahaines1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/507)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[`upload_and_setoff_workflows.py` line 655 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/507#-Nh2LwOXDpINzoDwRG5K:-Nh6bUdXAlDB9bk-CcgF:b-keugmn) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/b5bc093e5cd853b5c22cddfb2016234f94094794/upload_and_setoff_workflows.py#L655)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

The TSO samplesheet template has a 25 line header. I tried doing this the other way round by I couldn't get the whole header and separate the sample lines at the same time. This is at least partly becuase of the need to handle empty lines at the end (i.e. lines that just contain ",,,,,,,") as there are some lines like this in the header too.
</blockquote></details>

changed this to have separate sections to capture the samples and the header

**Review by aledj2 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/507)* status: 1 of 2 files reviewed, all discussions resolved

___
*[`upload_and_setoff_workflows.py` line 653 at r4](https://reviewable.io/reviews/moka-guys/automate_demultiplex/507#-NhB28hz0DiCQiOFfHZK:-NhB28hz0DiCQiOFfHZL:biosswq) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/0db361266ce7557e8cabad5975b4e6f7f1fac9f6/upload_and_setoff_workflows.py#L653)):*
> ```Python
>         samples = []
>         no_sample_lines = 0
>         expected_data_headers = ["Sample_ID", "Sample_Name", "index"]
> ```

I think including index is ok for TSO runs but I'm a little uneasy about including this here as it's the sort of thing that could quite feasibly be added to samplesheet header in future - I think sample_ID and Sample_Name should be sufficient, perhaps with "AND" not "OR" (any) - maybe consider for future revision?

**Review by aledj2 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/507)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rebeccahaines1)

**Pull request merged**
