### PR TITLE
V40.0.0 attempt2

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/349)

### CODE REVIEW

**Review by Graeme-Smith — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/349)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @aledj2)

___
*[automate_demultiplex_config.py, line 117 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/349#-MfIOJlQ6ksWWxcoli8q:-MfIOJlQ6ksWWxcoli8r:bkpt80e) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/af72e84e6d8b1e4b1b3a7659c7758fcbfd43cde5/automate_demultiplex_config.py#L117)):*
> ```Python
> mokawes_pipeline_ID = "4318"
> # MokaAMP ID
> mokaamp_pipeline_ID = "4725"
> ```

Why has this changed from 4274 to 4725?
___
*[demultiplex.py, line 269 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/349#-MfIOr7UAm8KPYnO5ll4:-MfIOr7UAm8KPYnO5ll5:b-edqizc) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/af72e84e6d8b1e4b1b3a7659c7758fcbfd43cde5/demultiplex.py#L269)):*
> ```Python
>         #for samplesheet in os.listdir(self.samplesheets)
>             #self.list_of_samplesheets.append(samplesheet.upper())
> ```

Why is the commented-out code no longer needed?
___
*[demultiplex.py, line 384 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/349#-MfIPA5H50Kgxc8Oib6p:-MfIPA5H50Kgxc8Oib6q:b-6bomqx) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/af72e84e6d8b1e4b1b3a7659c7758fcbfd43cde5/demultiplex.py#L384)):*
> ```Python
>             # Run the bcl2fastq command to start demultiplexing. the script won't continue until this
>             # process finishes. Stderr and stdout streams are redirected to the log file by the command
>             
> ```

So the below code should not now be skipped if config.testing?
___
*[demultiplex.py, line 643 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/349#-MfIPaFwBYN5e6CxxGgw:-MfIPaFwBYN5e6CxxGgx:b-6bomqx) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/af72e84e6d8b1e4b1b3a7659c7758fcbfd43cde5/demultiplex.py#L643)):*
> ```Python
>                     return True
>                 # if integrity check failed...
>                 else:
> ```

So the below code should not now be skipped if config.testing?

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/349)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @Graeme-Smith)

___
*[automate_demultiplex_config.py, line 117 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/349#-MfIOJlQ6ksWWxcoli8q:-MfIZ14KDhBCSK2V2jDt:bs2f74e) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/af72e84e6d8b1e4b1b3a7659c7758fcbfd43cde5/automate_demultiplex_config.py#L117)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Why has this changed from 4274 to 4725?
</blockquote></details>

The pipelineID is in the item table in Moka.It allows us to record which version of the pipeline was used to process the data. it is used in the sql queries 
___
*[demultiplex.py, line 269 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/349#-MfIOr7UAm8KPYnO5ll4:-MfIZA6q9e2MAY4wOPTE:b-5af60e) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/af72e84e6d8b1e4b1b3a7659c7758fcbfd43cde5/demultiplex.py#L269)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Why is the commented-out code no longer needed?
</blockquote></details>

As per https://github.com/moka-guys/automate_demultiplex/issues/342 this test was found to be incorrect. This line used to allow for differences in the capitalisation of the samplesheet when checking for the presence, but 1) we shouldn't allow for this, and 2) if the samplesheet is there with an incorrect case the process would fail at a later date for eg bcl2fastq wouldn;t find the file. The issue here is that if the specified samplesheet can't be found bcl2fastq looks elsewhere and if it can find a samplesheet elsewhere within the runfolder it may use that. This would not have been checked and may be out of date.

This code should have been deleted not commented out.
___
*[demultiplex.py, line 384 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/349#-MfIPA5H50Kgxc8Oib6p:-MfI_2r3EzZeZE4l9Vv4:bx2mmic) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/af72e84e6d8b1e4b1b3a7659c7758fcbfd43cde5/demultiplex.py#L384)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

So the below code should not now be skipped if config.testing?
</blockquote></details>

config.debug used to be used for testing/development before being used to developing unit tests that were never implemented. The config.debug was used in a else-if loop where the functions were not called but a print statement instead.
___
*[demultiplex.py, line 643 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/349#-MfIPaFwBYN5e6CxxGgw:-MfIaSxM5KhDgkYjawg_:b7bwsca) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/af72e84e6d8b1e4b1b3a7659c7758fcbfd43cde5/demultiplex.py#L643)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

So the below code should not now be skipped if config.testing?
</blockquote></details>

This just stopped sending an email if integrity check failed, but it doesn't hurt to send this

**Review by Graeme-Smith — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/349)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Review by Graeme-Smith — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/349)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
