### PR TITLE
V45.1.0

### PR DESCRIPTION
**Pull request by RachelDuffin**
- Update upload agent version to v 1.5.33 in line with the version used for archer archiving, as per DNAnexus recommendation
- Add functionality to process OncoDEEP runs (using the live OncoDEEP pan number), including oncodeep_upload v1.0.0 app
- Address jinja2 dependabot security alert – update jinja2 to v3.1.4
- Update naming of ‘master’ branch to ‘main’ - ‘main’ is the current widely accepted nomenclature for the primary branch 
- Update oncology ops email used as the recipient for the pipeline started emails
- Move copying of the samplesheet from setoff_workflows module to demultiplexing module
- Add auth string variable assignment to top of all commands files – simplifies creation / writing of commands to file
- Remove TSO low throughput pan number (Pan4969)
- Update duty csv version to v1.4.0
- Update samplesheet validator to v1.3.0
- Fix white space addition in SQL emails
- Update pipeline IDs
- Custom Panels – ID in use was for a previous version of the pipeline
- Archer – MultiQC was not listed in previous ID
- TSO – previous ID had no information listed about the app versions
- OncoDEEP – new pipeline
- Set logger mode to 'w' so logging overwrites old logs
- Add functionality to process development runs without UMIs (demultiplex, then upload the runfolders including BCLs, and set off fastqc / multiqc)
- Add new development pan number for development runs with UMIs (Pan5227), and functionality to handle these (creates flag files to prevent demultiplexing and runfolder upload)
- Add UMI dev runfolder to config
- Addition to toolbox of RunfolderSamples class (derived from CollectRunfolderClass class in setoff_workflows) containing runfolder properties derived from the samplesheet, and SampleObject class originally in setoff_workflows
- Alter behaviour to prevent firing of md5sum absence warnings (as there is a period of time after sequencing finishes before the file appears)
- Fix so that SampleSheet is checked prior to the run finishing sequencing
- Fix issue where setoff_workflows falls over for TSO runs as the samplehseet has not been copied over to the runfolder from the samplesheets directory
- Fix issue where setoff workflows tries to automatically upload runs with the development pan number
- Make setoff_workflows more modular (Creation of classes per run type for collating commands generation, to make the logic easier to follow. Move dx run command functions to new build_dx_commands script. Move PipelineEmails to pipeline_emails script)
- Remove Upload MultiQC as a dependency for duty_csv – addresses issue where duty_csv fails meaning that MultiQC reports cannot be uploaded to the genomics server i.e. upload multiqc fails
- Sort fastqs before validation so it is easier to see how far through we are 
- Remove requirement to specify command line auth token for upload runfolder script – the script will only ever be run from the workstation, where the auth key file resides in the same location, so this makes it more user friendly 
- Improve md5sum checking behaviour – If the runfolder requires no checksum checking (i.e. is a MiSeq), or the runfolder requires checksum checking and the checksum file exists: Check sequencing is complete If the sequencer requires no checksum checking (is a MiSeq) or the integrity check passes (checksum file exists and either has been checked before and contains the checksum success message, or has not been checked before in which case the check is carried out) If the above criteria are satisfied, processing continues 
- Comment out addition of upload_multiqc command to dx run commands script 
- Update requirements file to ensure it captures all dependencies 
- Change missing fastqs logger message to warning 

This change is [Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/546)

### CODE REVIEW

**Review by rebeccahaines1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 24 files at r1, 15 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/546)* status: 20 of 25 files reviewed, 3 unresolved discussions (waiting on @RachelDuffin)

___
*[`config/ad_config.py` line 417 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/546#-O1GmjawEvHmcDzRZ-te:-O1GmjawEvHmcDzRZ-tf:b-pf698j) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/b5d69dfdc76eb1b5c69d84be30930fea27ff3e64/config/ad_config.py#L417)):*
> ```Python
>     RUNFOLDERS = RUNFOLDERS
>     PROD_ORGANISATION = "org-viapath_prod"  # Prod org for billing
>     if BRANCH == "master":  # Prod branch
> ```

branch is "main" not "master" I think?
___
*[`demultiplex/demultiplex.py` line 719 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/546#-O1GsqUyEaeSjGlpEYV0:-O1GsqUyEaeSjGlpEYV1:btvchzk) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/b5d69dfdc76eb1b5c69d84be30930fea27ff3e64/demultiplex/demultiplex.py#L719)):*
> ```Python
>             self.demux_rf_logger.info(self.demux_rf_logger.log_msgs["no_demultiplexing"], self.pipeline)
>             return True
>         else:  # All other runs require demultiplexing
> ```

add to comment "apart from development runs containing UMIs- these are already excluded". ?is this the case?
___
*[`test/test_demultiplex.py` line 562 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/546#-O1GyARA8lpeyCnTL37y:-O1GyARA8lpeyCnTL37z:b-2gjkg3) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/b5d69dfdc76eb1b5c69d84be30930fea27ff3e64/test/test_demultiplex.py#L562)):*
> ```Python
>     #         ad_logger.shutdown_logs(dr_obj.demux_rf_logger)
> 
>     # def test_setoff_workflow_fail(self, demultiplexing_notrequired):
> ```

why is this test and the one above commented out? Can you add a note in the docstring for each clarifying this please? Will make it easier for future developers to understand. thanks

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/546)* status: 10 of 30 files reviewed, 3 unresolved discussions (waiting on @RachelDuffin and @rebeccahaines1)

___
*[`config/ad_config.py` line 417 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/546#-O1GmjawEvHmcDzRZ-te:-O1H-yMP2OwGkmymosrc:bevvyqp) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/b5d69dfdc76eb1b5c69d84be30930fea27ff3e64/config/ad_config.py#L417)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

branch is "main" not "master" I think?
</blockquote></details>

Good spot - fixed
___
*[`demultiplex/demultiplex.py` line 719 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/546#-O1GsqUyEaeSjGlpEYV0:-O1H17QU5AxioZ0zzuhV:ba0jolr) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/b5d69dfdc76eb1b5c69d84be30930fea27ff3e64/demultiplex/demultiplex.py#L719)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

add to comment "apart from development runs containing UMIs- these are already excluded". ?is this the case?
</blockquote></details>

Have removed the self.tso if statement as this is a hangover from before the runtype\_requires\_demultiplexing function (i.e. tso runs would never actually reach the run_demultiplexing functions so those lines of code are obsolete)
___
*[`test/test_demultiplex.py` line 562 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/546#-O1GyARA8lpeyCnTL37y:-O1H1bUm1dJDi03r3q-r:bd8mcff) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/b5d69dfdc76eb1b5c69d84be30930fea27ff3e64/test/test_demultiplex.py#L562)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

why is this test and the one above commented out? Can you add a note in the docstring for each clarifying this please? Will make it easier for future developers to understand. thanks
</blockquote></details>

This was something I was working on whilst you were doing the code review, I've made some changes since you've reviewed this

**Review by rebeccahaines1 — COMMENTED** [review]
> Reviewed 2 of 20 files at r2, 12 of 18 files at r3, 4 of 4 files at r4, 5 of 6 files at r5, 4 of 4 files at r6, 3 of 4 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/546)* status: 30 of 32 files reviewed, all discussions resolved (waiting on @RachelDuffin)

**Review by rebeccahaines1 — APPROVED** [review]
> Reviewed 11 of 11 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/546)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RachelDuffin)

**Pull request merged**
