### PR TITLE
v44.6.0

### PR DESCRIPTION
**Pull request by RachelDuffin**
This update incorporates the following changes:
- Re-add peddy to multiqc depends list
- Fix order of app dependency for TSO and Custom Panels pipelines (including addition of an extra dependency list for custom panels to stop RPKM depending on multiqc)
- Add updated duty_csv app version
- Remove non-required panel argument to fastqc command creation function
- Exclude NTC sambamba job from depends list for TSO samples
- Only add to depends_list if JOBID exists from the command for TSO fastqc sompy and sambamba
- Add extra log command for writing dx run commands to file
- Add support for R430 test indication (prostate panel) on VCP2
- Update VCP2 variant calling, coverage and RPKM bed files
- Add --priority flag to dx run commands that previously didn't have it
- Specify dnanexus v2 instance types for peddy, multiqc, upload multiqc, RPKM and congenica upload commands
- Increase timeout time on R134 runs from 6 to 12 hours

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/492)

### CODE REVIEW

**Review by natashapinto — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/492)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @RachelDuffin)

___
*[`automate_demultiplex_config.py` line 11 at r6](https://reviewable.io/reviews/moka-guys/automate_demultiplex/492#-NTYyc3D9gdaJwC78AF0:-NTYyc3E-oDYvI6Rude9:bpwewtm) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/c214b83c324ed2e1c3d42247a39168fcbbbf9d02/automate_demultiplex_config.py#L11)):*
> ```Python
> 
> # Set debug mode
> testing = True
> ```

assuming this is set as true because you're still testing?

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/492)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[`automate_demultiplex_config.py` line 11 at r6](https://reviewable.io/reviews/moka-guys/automate_demultiplex/492#-NTYyc3D9gdaJwC78AF0:-NTZOxbx54YlOuqACIZc:bn488y9) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/c214b83c324ed2e1c3d42247a39168fcbbbf9d02/automate_demultiplex_config.py#L11)):*
<details><summary><i>Previously, natashapinto (Natasha Pinto) wrote…</i></summary><blockquote>

assuming this is set as true because you're still testing?
</blockquote></details>

Ah yes, I will make sure to set back before asking for a merge. Thanks!

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/492)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[`automate_demultiplex_config.py` line 11 at r6](https://reviewable.io/reviews/moka-guys/automate_demultiplex/492#-NTYyc3D9gdaJwC78AF0:-NTmciZ15keZQ5reBNOJ:b-7oa7ce) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/c214b83c324ed2e1c3d42247a39168fcbbbf9d02/automate_demultiplex_config.py#L11)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Ah yes, I will make sure to set back before asking for a merge. Thanks!
</blockquote></details>

This has now been set back to False

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/492)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[`upload_and_setoff_workflows.py` line 411 at r7](https://reviewable.io/reviews/moka-guys/automate_demultiplex/492#-NTnJUWACl1MTmtug9bL:-NTnRNWN5xtavh4iF1Mc:b-886gsx) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/598d687bd0ef359166766e417af9f05cfc40ba72/upload_and_setoff_workflows.py#L411)):*
<details><summary><i>Previously, natashapinto (Natasha Pinto) wrote…</i></summary><blockquote>

why is this block of code commented out?
</blockquote></details>

Fixed

**Pull request merged**
