### PR TITLE
V37

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/312)

### CODE REVIEW

**Comment by Graeme-Smith** [comment]
___
*[automate_demultiplex_config.py, line 601 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/312#-MT0OJ3u6mw8iXDGJ27M:-MT0OJ3u6mw8iXDGJ27N:b-j9x330) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/c8934898cd8d5b85570bf4a5314946331ae5189e/automate_demultiplex_config.py#L601)):*
> ```Python
> 		"RPKM_also_analyse": vcp3_panel_list,
> 		"hsmetrics_bedfile": "Pan4278data.bed",
> 		"sambamba_bedfile": "Pan4278data.bed",
> ```


Should the Pan4278dataSambamba.bed file be used her?

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/312)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith)

___
*[automate_demultiplex_config.py, line 601 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/312#-MT0OJ3u6mw8iXDGJ27M:-MT0P3Y29OCPo50LMLv7:b-2yw6qu) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/c8934898cd8d5b85570bf4a5314946331ae5189e/automate_demultiplex_config.py#L601)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Should the Pan4278dataSambamba.bed file be used her?
</blockquote></details>

yes. good spot!

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/312)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith)

___
*[automate_demultiplex_config.py, line 601 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/312#-MT0OJ3u6mw8iXDGJ27M:-MT0Pk5g1pjSMl7QP4aA:b-896fix) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/c8934898cd8d5b85570bf4a5314946331ae5189e/automate_demultiplex_config.py#L601)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

yes. good spot!
</blockquote></details>

Done.

**Comment by Graeme-Smith** [comment]
___
*[automate_demultiplex_config.py, line 611 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/312#-MT0OZDbDjMsAXSvcrXF:-MT0OZDbDjMsAXSvcrXG:b1e5ais) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/c8934898cd8d5b85570bf4a5314946331ae5189e/automate_demultiplex_config.py#L611)):*
> ```Python
> 		"RPKM_also_analyse": vcp3_panel_list,
> 		"hsmetrics_bedfile": "Pan4278data.bed",
> 		"sambamba_bedfile": "Pan4278data.bed",
> ```

Should the Pan4278dataSambamba.bed file be used her?

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/312)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Graeme-Smith)

___
*[automate_demultiplex_config.py, line 611 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/312#-MT0OZDbDjMsAXSvcrXF:-MT0V6Dc0uJyz1Rwt99_:b-896fix) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/c8934898cd8d5b85570bf4a5314946331ae5189e/automate_demultiplex_config.py#L611)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Should the Pan4278dataSambamba.bed file be used her?
</blockquote></details>

Done.

**Review by Graeme-Smith — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/312)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
