### PR TITLE
automate exome depth

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506)

### CODE REVIEW

**Review by RachelDuffin — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506)* status: all files reviewed, 16 unresolved discussions (waiting on @aledj2)

___
*[`automate_demultiplex_config.py` line 11 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBLYSWEb1ZJGaUApMs:-NhBLYSXDNhpqQTfc_Fx:b-i7416f) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L11)):*
> ```Python
> 
> # Set debug mode
> testing = True
> ```

To change at end of testing
___
*[`automate_demultiplex_config.py` line 292 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBLnlV10AOTI_KNQ1F:-NhBLnlV10AOTI_KNQ1G:bngt7ba) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L292)):*
> ```Python
> ED_VCP2_readcount_BEDfile_pannum = "Pan5188_exomedepth.bed" 
> #VCP3 normals data file
> ED_readcount_normals_VCP3_file=None#"Pan5149_normals_v1.0.0.RData"
> ```

Should this have a file?
___
*[`automate_demultiplex_config.py` line 493 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBM3VW4yTK4CYrYPIF:-NhBM3VW4yTK4CYrYPIG:bkaxit6) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L493)):*
> ```Python
>     "Pan4146",  # VCP3 Viapath R81 (CM)
>     "Pan4149",  # VCP2 Viapath R208 (BRCA)
>     "Pan4150",  # VCP2 Viapath R207 (ovarian)
> ```

Was it intentional to remove Pan4127 and Pan4818?
___
*[`automate_demultiplex_config.py` line 609 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBMECA5AoTt5uoFiP2:-NhBMECA5AoTt5uoFiP3:b-9mw4yy) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L609)):*
> ```Python
>     "Pan4146",
>     "Pan4151",
>     #"Pan4043",
> ```

Should this be commented out?
___
*[`automate_demultiplex_config.py` line 767 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBN4eu7iRprEdmFX0M:-NhBN0sTByM8O_aq8_Za:bp2s2v2) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L767)):*
> ```Python
>     #     "variant_calling_bedfile": "Pan5119data.bed",
>     #     "sambamba_bedfile": "Pan5123dataSambamba.bed",
>     #     "exome_depth_cnvcalling_BED":  "PanXXXX"
> ```

Should these two pan numbers be commented out?
___
*[`automate_demultiplex_config.py` line 820 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBN8nZ8IkLYk_nqb_N:-NhBN8nZ8IkLYk_nqb_O:bp2s2v2) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L820)):*
> ```Python
>     #     "congenica_credentials": "STG",
>     #     "congenica_IR_template": "non-priority",
>     #     "congenica_project": "4201",
> ```

Should these two pan numbers be commented out?
___
*[`automate_demultiplex_config.py` line 1249 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBNIGx2IBh1DBn7sS3:-NhBNIGx2IBh1DBn7sS4:b1uzgr) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L1249)):*
> ```Python
>         "sambamba_bedfile": "Pan4995dataSambamba.bed",
>         "variant_calling_bedfile": "Pan4995data.bed",
>         # "exome_depth_cnvcalling_BED": "Pan5179", bedfile not yet made
> ```

Replace with bedfile?
___
*[`automate_demultiplex_config.py` line 1440 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBNbdd5Z3C-CjOwsEk:-NhBNbdd5Z3C-CjOwsEl:b1uzgr) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L1440)):*
> ```Python
>         "variant_calling_bedfile": "Pan4995data.bed",
>         "sambamba_bedfile": "Pan4995dataSambamba.bed",
>         # "exome_depth_cnvcalling_BED": "Pan5174" BEDfile not yet available
> ```

Replace with bedfile?
___
*[`automate_demultiplex_config.py` line 1503 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBNdIh2BZXAiVZjWne:-NhBNdIh2BZXAiVZjWnf:b1uzgr) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L1503)):*
> ```Python
>         "variant_calling_bedfile": "Pan4995data.bed",
>         "sambamba_bedfile": "Pan4995dataSambamba.bed",
>         #"exome_depth_cnvcalling_BED": "Pan5179" BEDfile not yet available
> ```

Replace with bedfile?
___
*[`automate_demultiplex_config.py` line 1597 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBNhZ51pKplFotaPK9:-NhBNhZ51pKplFotaPKA:byp18fd) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L1597)):*
> ```Python
>         "sambamba_bedfile": "Pan5018dataSambamba.bed",
>         "masked_reference": "project-ByfFPz00jy1fk6PjpZ95F27J:file-GF84GF00QfBfzV35Gf8Qg53q",  # hs37d5_Pan4967.bwa-index.tar.gz
>         
> ```

Remove
___
*[`automate_demultiplex_config.py` line 1610 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBNifQ30JKT_9lGwEX:-NhBNifR-xfLLzQjCQHH:byp18fd) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L1610)):*
> ```Python
>         "sambamba_bedfile": "Pan5018dataSambamba.bed",
>         "masked_reference": "project-ByfFPz00jy1fk6PjpZ95F27J:file-GF84GF00QfBfzV35Gf8Qg53q",  # hs37d5_Pan4967.bwa-index.tar.gz
>         
> ```

Remove
___
*[`automate_demultiplex_config.py` line 1780 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBNlTo6f9fJdy-lWMi:-NhBNlTo6f9fJdy-lWMj:bbp2aea) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L1780)):*
> ```Python
>     "tso_pannumbers": "-itso_pannumbers=Pan4969,Pan5085,Pan5114",
>     "stg_pannumbers": (
>         "-istg_pannumbers=Pan4821,Pan4822,Pan4823,Pan4824,Pan4825,Pan4816,Pan4817,Pan4819,Pan4820,"
> ```

Why have these pan numbers been removed?
___
*[`upload_and_setoff_workflows.py` line 122 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBQ_vB-ypdXDBrBZN6:-NhBQ_vB-ypdXDBrBZN7:b-vs7r4d) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/upload_and_setoff_workflows.py#L122)):*
> ```Python
>             + "_TSO_post_run_commands.sh"
>         )
>         #TODO copy lines above to create separate dx run commands output script for TSO (to be run by duty binfx)
> ```

To do or delete
___
*[`upload_and_setoff_workflows.py` line 644 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBQpwV2pZmRLfnFEki:-NhBQpwV2pZmRLfnFEkj:bhyb8ns) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/upload_and_setoff_workflows.py#L644)):*
> ```Python
>         take TSO500 samplesheet and split in to parts with <=16 samples/sheet
>         write samplesheets to runfolder
>         return list of samplesheet paths? or just names (if they're saved in the runfolder, 
> ```

Clarify / remove the '?'
___
*[`upload_and_setoff_workflows.py` line 1795 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBRuUR8kfYLMaeDl9_:-NhBRuUR8kfYLMaeDl9a:b-h1mdqw) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/upload_and_setoff_workflows.py#L1795)):*
> ```Python
>                 command_list.append(self.build_ED_cnv_calling_cmd(panel))
> 
>         return command_list
> ```

Add a space after the function
___
*[`upload_and_setoff_workflows.py` line 2363 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBS9RoEqQFnAsOZQ4h:-NhBS9RoEqQFnAsOZQ4i:b-3akay5) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/upload_and_setoff_workflows.py#L2363)):*
> ```Python
>         return cleaned_list
> 
>     # TODO set this up so it only runs the RPKM app if there are enough samples files (minimum 3 required by the app)
> ```

To resolve?

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506)* status: all files reviewed, 16 unresolved discussions (waiting on @RachelDuffin)

___
*[`automate_demultiplex_config.py` line 292 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBLnlV10AOTI_KNQ1F:-NhBTBf5BfKxSGix0AzV:beyyse6) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L292)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Should this have a file?
</blockquote></details>

this hasn't been made yet (this is why exome depth doesn't support vcp3)
___
*[`automate_demultiplex_config.py` line 493 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBM3VW4yTK4CYrYPIF:-NhBTQG-CtKSqmISTyyI:b-rtw6vu) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L493)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Was it intentional to remove Pan4127 and Pan4818?
</blockquote></details>

yes, this test (R209) has been withdrawn (combined with R211)
___
*[`automate_demultiplex_config.py` line 609 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBMECA5AoTt5uoFiP2:-NhBU3Tk-iDJBAhjziAU:bk93x2l) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L609)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Should this be commented out?
</blockquote></details>

have removed
___
*[`automate_demultiplex_config.py` line 767 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBN4eu7iRprEdmFX0M:-NhBU4bm1d8F_l6OhCWM:bc3tmdx) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L767)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Should these two pan numbers be commented out?
</blockquote></details>

they aren't needed. have removed
___
*[`automate_demultiplex_config.py` line 820 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBN8nZ8IkLYk_nqb_N:-NhBU7cgAI7p282ZP8Ks:bc3tmdx) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L820)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Should these two pan numbers be commented out?
</blockquote></details>

they aren't needed. have removed
___
*[`automate_demultiplex_config.py` line 1249 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBNIGx2IBh1DBn7sS3:-NhBU9254o2F0jqwh720:b-of7cs0) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L1249)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Replace with bedfile?
</blockquote></details>

if this variable is commented out exome depth won't be called - this is commented out to flag that it will be turned on in future but what other actions may be needed. For many VCP3 tests these have gone to WGS, and for those that haven't CNV analysis isn't going to be assessed routinely, so creation of these BED files has been low priority.
___
*[`automate_demultiplex_config.py` line 1503 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBNdIh2BZXAiVZjWne:-NhBUvKg5F17stSlv_Td:b-of7cs0) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L1503)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Replace with bedfile?
</blockquote></details>

if this variable is commented out exome depth won't be called - this is commented out to flag that it will be turned on in future but what other actions may be needed. For many VCP3 tests these have gone to WGS, and for those that haven't CNV analysis isn't going to be assessed routinely, so creation of these BED files has been low priority.
___
*[`automate_demultiplex_config.py` line 1597 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBNhZ51pKplFotaPK9:-NhBV14z5dMo7KFEWYhH:b-896fix) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L1597)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`automate_demultiplex_config.py` line 1610 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBNifQ30JKT_9lGwEX:-NhBV1jmAkMLKU4IXrg5:b-896fix) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L1610)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`automate_demultiplex_config.py` line 1780 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBNlTo6f9fJdy-lWMi:-NhBV6et-9X0fyKffAt1:b-54on8y) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/automate_demultiplex_config.py#L1780)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Why have these pan numbers been removed?
</blockquote></details>

They are not R number specific, which is needed to perform exome depth
___
*[`upload_and_setoff_workflows.py` line 122 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBQ_vB-ypdXDBrBZN6:-NhBVJrq-ba2PrFsNlpi:b-896fix) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/upload_and_setoff_workflows.py#L122)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

To do or delete
</blockquote></details>

Done.
___
*[`upload_and_setoff_workflows.py` line 644 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBQpwV2pZmRLfnFEki:-NhBVipU65Tr0xBO0VHx:b-896fix) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/upload_and_setoff_workflows.py#L644)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Clarify / remove the '?'
</blockquote></details>

Done.
___
*[`upload_and_setoff_workflows.py` line 1795 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBRuUR8kfYLMaeDl9_:-NhBVm712cTgtlXl46cv:b-896fix) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/upload_and_setoff_workflows.py#L1795)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Add a space after the function
</blockquote></details>

Done.
___
*[`upload_and_setoff_workflows.py` line 2363 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhBS9RoEqQFnAsOZQ4h:-NhBVr-p4NJX36UwzthH:b-896fix) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/f374faeb07c88b2435120a87a35ea9052470a58c/upload_and_setoff_workflows.py#L2363)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

To resolve?
</blockquote></details>

Done.

**Review by RachelDuffin — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2)

**Review by RachelDuffin — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @aledj2)

___
*[`upload_and_setoff_workflows.py` line 1571 at r4](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhCWozBA2Z-tuZQbYdt:-NhCWozBA2Z-tuZQbYdu:b-ka6r0e) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/49686483bcb4dc1b8b693fb3bd6e8a545fac2725/upload_and_setoff_workflows.py#L1571)):*
> ```Python
>                 # If panel is to be processed using mokapipe
>                 if self.panel_dictionary[panel]["mokapipe"]:
>                     commands_list.append("#For each sample there are 5 lines of commands. The dx run command for the workflow. and the jobid is then added to two depends_on lists.")
> ```

Are these and other comments going to be removed?

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @aledj2)

___
*[`upload_and_setoff_workflows.py` line 689 at r4](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhCWxn0BlY8qM4_j9KL:-NhCWxn0BlY8qM4_j9KM:b-nypbkf) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/49686483bcb4dc1b8b693fb3bd6e8a545fac2725/upload_and_setoff_workflows.py#L689)):*
> ```Python
>         number_of_batches = len(batches)
>         #capture path for samplesheet in runfolder
>         runfolder_samplesheet_file = samplesheet_file = os.path.join(self.runfolder_obj.runfolderpath, self.runfolder_obj.runfolder_samplesheet_name)
> ```

Is this a mistake?

**Review by RachelDuffin — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506)* status: all files reviewed, 3 unresolved discussions (waiting on @aledj2)

**Review by rebeccahaines1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @aledj2 and @RachelDuffin)

___
*[`upload_and_setoff_workflows.py` line 689 at r4](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhCWxn0BlY8qM4_j9KL:-NhCgx_zDygdYTWe7ycj:b5siprq) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/49686483bcb4dc1b8b693fb3bd6e8a545fac2725/upload_and_setoff_workflows.py#L689)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Is this a mistake?
</blockquote></details>

yes, changed this now
___
*[`upload_and_setoff_workflows.py` line 1571 at r4](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506#-NhCWozBA2Z-tuZQbYdt:-NhCgvuM0yyhgYS-ixE5:bb7f2mf) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/49686483bcb4dc1b8b693fb3bd6e8a545fac2725/upload_and_setoff_workflows.py#L1571)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Are these and other comments going to be removed?
</blockquote></details>

done

**Review by RachelDuffin — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2)

**Review by natashapinto — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/506)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Comment by rebeccahaines1** [comment]
PR being closed without merge because set up incorrectly- should have been set to merge feature to development branch

**Pull request closed without merging**
