### PR TITLE
V43.0.2

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/373)

### CODE REVIEW

**Review by RachelDuffin — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/373)* status: all files reviewed, 2 unresolved discussions (waiting on @aledj2)

___
*[automate_demultiplex_config.py, line 11 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/373#-MtMz1IV5_Lj4G0T3mKs:-MtMz1IV5_Lj4G0T3mKt:b-tix7qk) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/df762432ffa6b27638cd8a6878ba1a33366d264e/automate_demultiplex_config.py#L11)):*
> ```Python
> 
> # Set debug mode
> testing = True
> ```

Set back to false
___
*[upload_and_setoff_workflows.py, line 2384 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/373#-MtN0qgF4sZqxDJ9TJve:-MtN0qgGBii31Hl2ks2H:b-q5r8ey) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/df762432ffa6b27638cd8a6878ba1a33366d264e/upload_and_setoff_workflows.py#L2384)):*
> ```Python
>             )
>             email_priority = 1  # high priority
>             email_message = (
> ```

If you wanted to reduce the amount of code here the repeated email_message blocks could always be moved to their own email_message function

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/373)* status: all files reviewed, 2 unresolved discussions (waiting on @aledj2 and @RachelDuffin)

___
*[upload_and_setoff_workflows.py, line 2384 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/373#-MtN0qgF4sZqxDJ9TJve:-MtN5874CiNQpVhpa1NT:b-ys2x45) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/df762432ffa6b27638cd8a6878ba1a33366d264e/upload_and_setoff_workflows.py#L2384)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

If you wanted to reduce the amount of code here the repeated email_message blocks could always be moved to their own email_message function
</blockquote></details>

I did look at doing this but you still need to build each different email template (at least 3 different emails are sent), populate these and then pass the email message object to the send_an email function. I think this becomes a little harder to piece together what the email is saying. eg:

```sql_email_message = ("%s %s being processed using workflow(s) %s\n\nPlease update Moka using the below queries and ensure that \
            %s records are updated:\n\n%s\n\n") 
self.send_an_email(config.you, email_subject, sql_email_message % (% (config.test_email_header, self.runfolder_obj.runfolder_name,",".join(self.sql_queries["oncology"]["workflows"]),str(self.sql_queries["oncology"]["count"]),"\n".join(self.sql_queries["oncology"]["query"]))), email_priority)```

I think this would only reduce 2 or possibly 3 email message blocks as they are all slightly different, and the more flexible or OO you make the template the more code you need elsewhere to populate them.

Very open to other approaches/suggestions!
```

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/373)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @aledj2 and @RachelDuffin)

___
*[upload_and_setoff_workflows.py, line 2384 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/373#-MtN0qgF4sZqxDJ9TJve:-MtN_2De1RQprl67ScZf:brhbin4) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/df762432ffa6b27638cd8a6878ba1a33366d264e/upload_and_setoff_workflows.py#L2384)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

I did look at doing this but you still need to build each different email template (at least 3 different emails are sent), populate these and then pass the email message object to the send_an email function. I think this becomes a little harder to piece together what the email is saying. eg:

```sql_email_message = ("%s %s being processed using workflow(s) %s\n\nPlease update Moka using the below queries and ensure that \
            %s records are updated:\n\n%s\n\n") 
self.send_an_email(config.you, email_subject, sql_email_message % (% (config.test_email_header, self.runfolder_obj.runfolder_name,",".join(self.sql_queries["oncology"]["workflows"]),str(self.sql_queries["oncology"]["count"]),"\n".join(self.sql_queries["oncology"]["query"]))), email_priority)```

I think this would only reduce 2 or possibly 3 email message blocks as they are all slightly different, and the more flexible or OO you make the template the more code you need elsewhere to populate them.

Very open to other approaches/suggestions!
```

</blockquote></details>

made these changes

**Review by RachelDuffin — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/373)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[upload_and_setoff_workflows.py, line 2384 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/373#-MtN0qgF4sZqxDJ9TJve:-MtNeKyE6xpCLfgpohdH:bb81o7i) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/df762432ffa6b27638cd8a6878ba1a33366d264e/upload_and_setoff_workflows.py#L2384)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

made these changes
</blockquote></details>

Looks good, I see what you mean about the templates being slightly different so it being hard to cut it down

**Review by RachelDuffin — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/373)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
