### PR TITLE
Prostate panel r430

### PR DESCRIPTION
**Pull request by rebeccahaines1**
Support for R430 prostate panel, and update of VCP2 core pan numbers

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/493)

### CODE REVIEW

**Review by aledj2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/493)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @rebeccahaines1)

___
*[`automate_demultiplex_config.py` line 263 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/493#-NTNta8PE48xZSi2PGI-:-NTNta8PE48xZSi2PGI0:bcw2bx9) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/840b09298a38523c84c43470bb44c86c4b005720/automate_demultiplex_config.py#L263)):*
> ```Python
> )
> mokapipe_GATK_human_exome_appletID = "applet-FYZ097j0jy1ZZPx30GykP63J"
> mokapipe_FH_GATK_timeout_args = ( #TODO change timeout time
> ```

still a todo?
___
*[`automate_demultiplex_config.py` line 1165 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/493#-NTNtErSDALJfthPT36S:-NTNtErSDALJfthPT36T:b-7p10c6) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/840b09298a38523c84c43470bb44c86c4b005720/automate_demultiplex_config.py#L1165)):*
> ```Python
>         "congenica_upload": False,
>         "variant_calling_bedfile": "Pan4577data.bed",
>         "hsmetrics_bedfile": "Pan4949data.bed",
> ```

not urgent, considering this pipeline is pretty much obsolete but can you add a comment here saying this should also use the new BED file (and Pan4579 also)

**Review by rebeccahaines1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/493)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @aledj2)

___
*[`automate_demultiplex_config.py` line 263 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/493#-NTNta8PE48xZSi2PGI-:-NTNy6Ah3wuZ_AULuW74:b3f9dfo) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/840b09298a38523c84c43470bb44c86c4b005720/automate_demultiplex_config.py#L263)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

still a todo?
</blockquote></details>

Done. sorry I lost track of this. Have changed it now.
___
*[`automate_demultiplex_config.py` line 1165 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/493#-NTNtErSDALJfthPT36S:-NTO12wRDJ8zy4L87Kjl:b-896fix) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/840b09298a38523c84c43470bb44c86c4b005720/automate_demultiplex_config.py#L1165)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

not urgent, considering this pipeline is pretty much obsolete but can you add a comment here saying this should also use the new BED file (and Pan4579 also)
</blockquote></details>

Done.

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/493)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @rebeccahaines1)

___
*[`automate_demultiplex_config.py` line 1165 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/493#-NTNtErSDALJfthPT36S:-NTO7CxN10Iksx73b-rE:b-c0rzv9) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/840b09298a38523c84c43470bb44c86c4b005720/automate_demultiplex_config.py#L1165)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm really sorry, I think we only need to change the hsmetrics files here - the variant calling ones are panel specific in these cases

**Review by rebeccahaines1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/493)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[`automate_demultiplex_config.py` line 1165 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/493#-NTNtErSDALJfthPT36S:-NTOAfElDlZ9sJQksJMk:b-896fix) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/840b09298a38523c84c43470bb44c86c4b005720/automate_demultiplex_config.py#L1165)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

I'm really sorry, I think we only need to change the hsmetrics files here - the variant calling ones are panel specific in these cases
</blockquote></details>

Done.

**Review by aledj2 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/493)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rebeccahaines1)

**Pull request merged**
