### PR TITLE
Feature/mokapipe v2.17

### PR DESCRIPTION
**Pull request by RachelDuffin**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/464)

### CODE REVIEW

**Comment by RachelDuffin** [comment]
- Update mokapipe pipeline (including addition of new polyedge app)
- Update mokapipe pipeline ID
- Some minor formatting improvements

**Review by rebeccahaines1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/464)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2, @natashapinto, @preciserobot, and @RachelDuffin)

___
*[`automate_demultiplex_config.py` line 374 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/464#-NKOQS4q8UQBqJEzuglH:-NKOQS4q8UQBqJEzuglI:bti00lk) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/27603adfcb6197c920c45b5c11a64a604df3ab2f/automate_demultiplex_config.py#L374)):*
> ```Python
> # are applied at the point of analysis, so R and M numbers for these are not listed below
> 
> # Panel numbers for TSO do not refer to bed files, but refer to DNAnexus configuration (instance type,
> ```

I think this line should be removed and just add TSO to the list above (WES, Swift, Archer etc) as the same applies to them (i.e. the pan number doesn't necessarily refer to a bed file for any of these.

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/464)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @aledj2, @natashapinto, @preciserobot, and @rebeccahaines1)

___
*[`automate_demultiplex_config.py` line 374 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/464#-NKOQS4q8UQBqJEzuglH:-NKOYTrt-YrvC0BWm2RY:b-iry7x8) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/27603adfcb6197c920c45b5c11a64a604df3ab2f/automate_demultiplex_config.py#L374)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

I think this line should be removed and just add TSO to the list above (WES, Swift, Archer etc) as the same applies to them (i.e. the pan number doesn't necessarily refer to a bed file for any of these.
</blockquote></details>

Done, thanks

**Review by rebeccahaines1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/464)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2, @natashapinto, and @preciserobot)

**Pull request merged**
