### PR TITLE
try to fix tso500 tarball creation

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/369)

### CODE REVIEW

**Review by rebeccahaines1 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/369)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Review by rebeccahaines1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/369)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[upload_and_setoff_workflows.py, line 1440 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/369#-Mraby4Z7O9AVdq1hPjX:-Mraby4Z7O9AVdq1hPjY:b-919t3h) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/8393782246a7252ee6ff966557138ea3243ec8cc/upload_and_setoff_workflows.py#L1440)):*
> ```Python
>         # build dictionary of pan number specific/relevant bedfile to be used in command
>         #TODO what happens if we have multiple Pan numbers?
>         bedfiles = self.nexus_bedfiles("Pan4709")
> ```

Still Pan4709?

**Review by rebeccahaines1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/369)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @aledj2 and @rebeccahaines1)

**Review by rebeccahaines1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/369)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2)

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/369)* status: all files reviewed, 1 unresolved discussion (waiting on @rebeccahaines1)

___
*[upload_and_setoff_workflows.py, line 1440 at r2](https://reviewable.io/reviews/moka-guys/automate_demultiplex/369#-Mraby4Z7O9AVdq1hPjX:-Mrassn-CU_mtYYiaUA_:b-896fix) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/8393782246a7252ee6ff966557138ea3243ec8cc/upload_and_setoff_workflows.py#L1440)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

Still Pan4709?
</blockquote></details>

Done.

**Review by rebeccahaines1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/369)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
