### PR TITLE
V41.0.0

### PR DESCRIPTION
**Pull request by rebeccahaines1**
Update for MokaAMP v2.1 for all swift panels and remove mokaONC

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @rebeccahaines1)

___
*[automate_demultiplex_config.py, line 117 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353#-Mj9O8PHDYxnmjGXPavz:-Mj9O8PHDYxnmjGXPaw-:b-3wz3uq) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/7e05bbb18af3dd4690935afa5361ed03257b7c82/automate_demultiplex_config.py#L117)):*
> ```Python
> mokawes_pipeline_ID = "4318"
> # MokaAMP ID
> mokaamp_pipeline_ID = "4725"
> ```

I think also needs to be updated - have added to moka to get an ID . please use 4816

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @rebeccahaines1)

___
*[automate_demultiplex_config.py, line 235 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353#-Mj9U9fr-FdF9M3FzzL1:-Mj9U9fr-FdF9M3FzzL2:b-p3hcen) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/7e05bbb18af3dd4690935afa5361ed03257b7c82/automate_demultiplex_config.py#L235)):*
> ```Python
> mokaamp_varscan_strandfilter_stage = " -istage-FPzGjp80jy1V3Jvb5z6xfpfZ.strand_filter="
> mokaamp_mpileup_cov_level_stage = " -istage-FxypXb807p1zj3g8Jv45Y54P.min_coverage="
> ```

We can remove the mpileup app from the workflow
___
*[upload_and_setoff_workflows.py, line 1445 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353#-Mj9UQr4-bBlMa64SvOQ:-Mj9UQr4-bBlMa64SvOR:b-jhng4h) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/7e05bbb18af3dd4690935afa5361ed03257b7c82/upload_and_setoff_workflows.py#L1445)):*
> ```
>             config.mokaamp_mpileup_cov_level_stage,
>             self.panel_dictionary[pannumber]["clinical_coverage_depth"],
> ```
we can remove this app fromt he workflow

**Review by rebeccahaines1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @aledj2)

___
*[automate_demultiplex_config.py, line 117 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353#-Mj9O8PHDYxnmjGXPavz:-MjTGcUpBIGQUSwXPDD5:bj4z2w0) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/7e05bbb18af3dd4690935afa5361ed03257b7c82/automate_demultiplex_config.py#L117)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

I think also needs to be updated - have added to moka to get an ID . please use 4816
</blockquote></details>

I wondered about this. Where does the new number come from?
___
*[automate_demultiplex_config.py, line 235 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353#-Mj9U9fr-FdF9M3FzzL1:-MjTGl56DLpyfa91PODt:b-tywstv) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/7e05bbb18af3dd4690935afa5361ed03257b7c82/automate_demultiplex_config.py#L235)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

We can remove the mpileup app from the workflow
</blockquote></details>

Mpileup is in the version that's in 001 and has been validated. I thought we agreed that it would be left in for now and taken out later?
___
*[upload_and_setoff_workflows.py, line 1445 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353#-Mj9UQr4-bBlMa64SvOQ:-MjTH-qp-P4RRwxBe4Bh:bk1l2n5) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/7e05bbb18af3dd4690935afa5361ed03257b7c82/upload_and_setoff_workflows.py#L1445)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
>             config.mokaamp_mpileup_cov_level_stage,
>             self.panel_dictionary[pannumber]["clinical_coverage_depth"],
> ```
we can remove this app fromt he workflow
</blockquote></details>

see prev comment- mpileup is in mokaamp v2.1 in 001

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[automate_demultiplex_config.py, line 235 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353#-Mj9U9fr-FdF9M3FzzL1:-MjTjutABQWVsVl7x_2s:b-t77xc3) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/7e05bbb18af3dd4690935afa5361ed03257b7c82/automate_demultiplex_config.py#L235)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

Mpileup is in the version that's in 001 and has been validated. I thought we agreed that it would be left in for now and taken out later?
</blockquote></details>

agreed
___
*[upload_and_setoff_workflows.py, line 1445 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353#-Mj9UQr4-bBlMa64SvOQ:-MjTjxN004n80HUFYMEz:b-t77xc3) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/7e05bbb18af3dd4690935afa5361ed03257b7c82/upload_and_setoff_workflows.py#L1445)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

see prev comment- mpileup is in mokaamp v2.1 in 001
</blockquote></details>

agreed

**Review by rebeccahaines1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[automate_demultiplex_config.py, line 117 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353#-Mj9O8PHDYxnmjGXPavz:-MjUU8E3B6cnQA8ty3tO:bn0gti8) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/7e05bbb18af3dd4690935afa5361ed03257b7c82/automate_demultiplex_config.py#L117)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

I wondered about this. Where does the new number come from?
</blockquote></details>

change made

**Review by aledj2 — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/353#-:-MjUpzXt9hOENrorecC2:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rebeccahaines1)

**Pull request merged**
