### PR TITLE
Feature/wscleaner incorporation

### PR DESCRIPTION
**Pull request by RachelDuffin**
- Incorporate workstation cleaner, with the addition of checking whether the runfolder is a development runfolder to prevent any deletion of dev runs

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549)

### CODE REVIEW

**Review by rebeccahaines1 — CHANGES_REQUESTED** [review]
> Reviewed 24 of 50 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549)* status: 22 of 50 files reviewed, 1 unresolved discussion (waiting on @RachelDuffin)

___
*[`config/ad_config.py` line 541 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549#-O1R0paY6LYU87BWjdP2:-O1R0paZ4ytyGnkJzjeA:bb7kj0e) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/fb88ea23505c36364c3246a8986d74fbbf462fcc/config/ad_config.py#L541)):*
> ```Python
>     Toolbox configuration
>     """
>     if BRANCH == "master":
> ```

main

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549)* status: 15 of 50 files reviewed, 1 unresolved discussion (waiting on @rebeccahaines1)

___
*[`config/ad_config.py` line 541 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549#-O1R0paY6LYU87BWjdP2:-O1R6_ZL2U37V4Q5TETB:b-up90lh) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/fb88ea23505c36364c3246a8986d74fbbf462fcc/config/ad_config.py#L541)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

main
</blockquote></details>

Just swapped this back - thanks!

**Review by rebeccahaines1 — CHANGES_REQUESTED** [review]
> Reviewed 15 of 50 files at r1, 1 of 1 files at r3, 13 of 19 files at r4, 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549)* status: 49 of 50 files reviewed, 2 unresolved discussions (waiting on @RachelDuffin)

___
*[`wscleaner/wscleaner.py` line 97 at r5](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549#-O1VmljYCUpVQhBzzjSk:-O1VmljYCUpVQhBzzjSl:b6k0y3d) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/d90ab6bdef8b5253c9059d715939ab3131b9d60c/wscleaner/wscleaner.py#L97)):*
> ```Python
>                                             Default is 6
>         """
>         self.runfolders_dir = runfolders_dir=RunfolderCleanupConfig.RUNFOLDERS
> ```

could this be:



_Code snippet:_
```Python
self.runfolders_dir = RunfolderCleanupConfig.RUNFOLDERS
```
___
*[`wscleaner/wscleaner.py` line 140 at r5](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549#-O1VnJHX7xHcrLPCBYFw:-O1VnJHX7xHcrLPCBYFx:b-3n00kp) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/d90ab6bdef8b5253c9059d715939ab3131b9d60c/wscleaner/wscleaner.py#L140)):*
> ```Python
>         runfolder_objects = []
>         folders = os.listdir(self.runfolders_dir)
>         # folders = self.get_dirs_created_after(self.runfolders_dir, '2024-06-12')  # V45.0.0 of the automated scripts (logfile number changed to 6)
> ```

is this line still needed?

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549)* status: 47 of 50 files reviewed, 2 unresolved discussions (waiting on @rebeccahaines1)

___
*[`wscleaner/wscleaner.py` line 97 at r5](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549#-O1VmljYCUpVQhBzzjSk:-O1VqXmwAKvJDsYcGLae:b-vo4tur) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/d90ab6bdef8b5253c9059d715939ab3131b9d60c/wscleaner/wscleaner.py#L97)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

could this be:
</blockquote></details>

Changed back - thanks!
___
*[`wscleaner/wscleaner.py` line 140 at r5](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549#-O1VnJHX7xHcrLPCBYFw:-O1VsEQl84mKuTBF3O0d:bpeceex) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/d90ab6bdef8b5253c9059d715939ab3131b9d60c/wscleaner/wscleaner.py#L140)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

is this line still needed?
</blockquote></details>

Yes - rea-added (it makes sure the scripts only looks at runs modified after the date of the automated scripts refactor release)

**Review by rebeccahaines1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 19 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549)* status: all files reviewed, 1 unresolved discussion (waiting on @RachelDuffin)

___
*[`setoff_workflows/setoff_workflows.py` line 810 at r5](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549#-O1VuR-409QuOmTAxKV9:-O1VuR-409QuOmTAxKVA:b-9g7tfi) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/d90ab6bdef8b5253c9059d715939ab3131b9d60c/setoff_workflows/setoff_workflows.py#L810)):*
> ```Python
>             :return None:
>         """
>         if self.rf_samples_obj.pipeline != "tso500":
> ```

and dev? or would dev runs not get to this point?2

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549)* status: all files reviewed, 1 unresolved discussion (waiting on @rebeccahaines1)

___
*[`setoff_workflows/setoff_workflows.py` line 810 at r5](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549#-O1VuR-409QuOmTAxKV9:-O1W-JBKC1IAoK1dPa-q:bhsezve) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/d90ab6bdef8b5253c9059d715939ab3131b9d60c/setoff_workflows/setoff_workflows.py#L810)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

and dev? or would dev runs not get to this point?2
</blockquote></details>

DIscussed

**Review by rebeccahaines1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/549)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RachelDuffin)

**Pull request merged**
