### PR TITLE
Lrpcr

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/411)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/411)* status: all files reviewed, 6 unresolved discussions (waiting on @aledj2 and @RachelDuffin)

___
*[`automate_demultiplex_config.py` line 11 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/411#-N8ZEaca7V7kH7zWPqo4:-N8ZMRMS4mR5e_sOv3kz:bb7s9xe) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/11a754d285ab32e13962321bb275478fb2040a70/automate_demultiplex_config.py#L11)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

I guess this will be removed at a later point
</blockquote></details>

yep!
___
*[`automate_demultiplex_config.py` line 200 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/411#-N8ZFGDG43MBpMVOVc0v:-N8ZMSvYDlM6pBjnqipd:b-ox6pt6) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/11a754d285ab32e13962321bb275478fb2040a70/automate_demultiplex_config.py#L200)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Was there no reference genome input before?
</blockquote></details>

The 'normal' reference genome is specified as a default input in the workflow so doesn't need to be given in the dx run cmd. If something is given in the dx run command is over writes the default
___
*[`automate_demultiplex_config.py` line 220 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/411#-N8ZFWma5rypW7bjAZWe:-N8ZMhtz0Otvu1eP5klE:bx6wyna) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/11a754d285ab32e13962321bb275478fb2040a70/automate_demultiplex_config.py#L220)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Again I don't understand why this wasn't in the config file before but it is now
</blockquote></details>

This is used in the timeout args below - this appletid wasn't required before that
___
*[`automate_demultiplex_config.py` line 493 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/411#-N8ZI7dF7HwycC0t2d2Z:-N8ZN-4pC7ISumZS8AfI:b-a1ewd7) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/11a754d285ab32e13962321bb275478fb2040a70/automate_demultiplex_config.py#L493)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

what does this do?
</blockquote></details>

The default panel properties dict defines all the possible properties/settings that can change between pan numbers. Adding masked_reference here allows us to overwrite the default bwa-index.reference.tar.gz (and allows for other references to be provided in the future for other panels)

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/411)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @aledj2 and @RachelDuffin)

___
*[`automate_demultiplex_config.py` line 371 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/411#-N8ZFlsu5Jto4PLpvAs_:-N8ZPfHC-u_VhdFRg34A:b86e53t) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/11a754d285ab32e13962321bb275478fb2040a70/automate_demultiplex_config.py#L371)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Very useful
</blockquote></details>

(fixes an issue raised by Rebecca)
___
*[`automate_demultiplex_config.py` line 449 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/411#-N8ZHCrq3eOuk7uetCOD:-N8ZPaXL303X9azBZe2J:bb7f2mf) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/11a754d285ab32e13962321bb275478fb2040a70/automate_demultiplex_config.py#L449)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Pan4573 needs replacing with Pan4579 - can be linked to fix this issue: https://github.com/moka-guys/automate_demultiplex/issues/408
</blockquote></details>

done

**Review by RachelDuffin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/411)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2)

**Review by RachelDuffin — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/411)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
